# To start the containers
# docker-compose -f docker-compose-servers.yaml up -d
# -d = run in detached mode

# To stop the containers
# docker-compose -f docker-compose-servers.yaml down -v
# -v = remove volumes as well.

# if we want to see the logs of any container
# docker logs <container_name>

# if we want to enter the container
# docker exec -it <container_name> bash

# To remove an image
# docker rmi <image_id/image_name>

# To stop a container
# docker stop <container_id>

# To remove a container
# docker rm <container_id>

version: '3.4'

networks:
  probable-cves:

services:
  probable-cves-api:
    container_name: probable-cves-api
    build:
        context: ./probable-cves-api
        dockerfile: ./Dockerfile
        # target: base-api
    volumes:
        - ./src:/src
    ports:
      - 5000:5000
    networks:
      - probable-cves

  probable-cves-ui:
    container_name: probable-cves-ui
    build:
        context: ./probable-cves-ui
        dockerfile: ./Dockerfile
        # target: base-ui
    volumes:
        - ./src/:/src
    ports:
        - 8080:8080
    links:
      - probable-cves-api
    networks:
      - probable-cves
